export const EditorRename = 'EditorRename'
export const InputBox = 'InputBox'
export const RenameDetails = 'RenameDetails'
export const RenameInputBox = 'RenameInputBox'
export const RenameInputWrapper = 'RenameInputWrapper'
export const Viewlet = 'Viewlet'
